### ISSUE TITLE
Node errors

### ISSUE THREAD

**Issue by gpeles** [Birch-san/box2d-wasm#32]
Hi!

Not sure this is an issue with your package or something wrong with my setup.

I'm using your package on the server, initialising it like so:
```
import Box2DFactory from 'box2d-wasm'

// then inside a singleton class:
this.b2 = await Box2DFactory()
```

This has an impact on how Node displays runtime errors. For example, here is the output I get if there's a type error (not related to box2d):
```
TypeError: Cannot read property 'graceTime' of undefined
/Users/gonipeles/Desktop/sc/game/scorecraft/node_modules/box2d-wasm/dist/umd/Box2D.js:12
q){e?d(e):c(q.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",oa),a.inspect=function(){return"[Emscripten Module object]"};else if(ea||ha)ha?ia=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ia=document.currentScript.src),_scriptDir&&(ia=_scriptDir),ia=0!==ia.indexOf("blob:")?ia.substr(0,ia.lastIndexOf("/")+1):"",ja=function(b){var c=new XMLHttpRequest;
                                                                                                                                                    ^

RuntimeError: abort(TypeError: Cannot read property 'graceTime' of undefined). Build with -s ASSERTIONS=1 for more info.
    at process.oa (/Users/gonipeles/Desktop/sc/game/scorecraft/node_modules/box2d-wasm/dist/umd/Box2D.js:16:62)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

The issue is that the actual file name and line number are not displayed.

If I comment out `this.b2 = await Box2DFactory()`, then the output is the following:
```
(node:18501) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'graceTime' of undefined
    at new WhacGame (webpack://scorecraft/./src/server/games/inner/Whac/WhacGame.ts?:45:41)
    at StandaloneInnerGame.eval (webpack://scorecraft/./src/server/games/outer/StandaloneInner/StandaloneInnerGame.ts?:95:42)
    at step (webpack://scorecraft/./src/server/games/outer/StandaloneInner/StandaloneInnerGame.ts?:66:23)
    at Object.eval [as next] (webpack://scorecraft/./src/server/games/outer/StandaloneInner/StandaloneInnerGame.ts?:47:53)
    at fulfilled (webpack://scorecraft/./src/server/games/outer/StandaloneInner/StandaloneInnerGame.ts?:38:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18501) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18501) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas for how to solve this?

**Comment by Birch-san** [comment]
from the error message, it looks like Emscripten modules install an `uncaughtException` handler:

```js
process.on("uncaughtException",function(b){throw b;})
```

I think your options are:  
- install your own `uncaughtException` handler (not sure how this will interact with the one Emscripten created)
- prevent an uncaught exceptions from propagating to the top of your application
  - for example, add a `try {} catch {}` around the code which is at risk of throwing errors.

**Comment by gpeles** [comment]
OK thanks!

Yes, I'm doing the latter but not always good at predicting which part of the code is at risk.

My current workaround is to comment out the initialisation of `Box2DFactory` whenever this happens and I'm not sure where the error is.
